export default {
  ADD_TAG_REQUEST: "ADD_TAG_REQUEST",
  ADD_TAG_SUCCESS: "ADD_TAG_SUCCESS",
  ADD_TAG_FAILURE: "ADD_TAG_FAILURE",
  DELETE_TAG_REQUEST: "DELETE_TAG_REQUEST",
  DELETE_TAG_SUCCESS: "DELETE_TAG_SUCCESS",
  DELETE_TAG_FAILURE: "DELETE_TAG_FAILURE"
};
