export default {
  GET_LISTS_FAILURE: "GET_LISTS_FAILURE",
  GET_LISTS_REQUEST: "GET_LISTS_REQUEST",
  GET_LISTS_SUCCESS: "GET_LISTS_SUCCESS",
  CREATE_LIST_REQUEST: "CREATE_LIST_REQUEST",
  CREATE_LIST_SUCCESS: "CREATE_LIST_SUCCESS",
  CREATE_LIST_FAILURE: "CREATE_LIST_FAILURE",
  CHANGE_NEW_LIST_NAME: "CHANGE_NEW_LIST_NAME",
  OPEN_NEW_LIST_FORM: "OPEN_NEW_LIST_FORM",
  RESET_NEW_LIST_FORM: "RESET_NEW_LIST_FORM",
  DELETE_LIST_REQUEST: "DELETE_LIST_REQUEST",
  DELETE_LIST_SUCCESS: "DELETE_LIST_SUCCESS",
  DELETE_LIST_FAILURE: "DELETE_LIST_FAILURE"
};
